cmsapp/urls.py
from django.urls import path
from cmsapp import views

app_name = 'cmsapp'
urlpatterns=[
  path('home/',views.CMSHome.as_view(),name='cmshome'),
]

inksynk/urls.py
from django.contrib import admin
from django.urls import path, include

# for static files during deployment
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('site/admin', admin.site.urls),
    path('',include("siteapp.urls")),
    path('cms/',include("cmsapp.urls")),
    path('cms/user/',include("userapp.urls")),
    path('cms/post/',include("postapp.urls")),
    # path('cms/dashboard/',include("dashboard.urls")),
    path('cms/class/',include("classapp.urls")),
    path('cms/comments/',include("commentapp.urls")),
    path('cms/admin/',include("adminapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postapp/urls.py
from django.urls import path
from postapp import views

app_name = 'postapp'
urlpatterns = [
    path('postapproval/<int:pk>', views.PostApproval.as_view(), name='postapproval'),
    path('newpost',views.CreatePostView.as_view(),name='newpost'),
    path('editpost/<int:pk>',views.EditPostView.as_view(),name='editpost'),
    path('drafts',views.ListDraftPosts.as_view(),name='draftposts'),
    
    path('published',views.ListPublishedPosts.as_view(),name='publishedposts'),
    path('published/<int:pk>',views.PublishedPostView.as_view(),name='publishedpost'),
    
    path('approved',views.ListApprovedPosts.as_view(),name='approvedposts'),
    path('listpostapproval',views.ListPostApproval.as_view(),name='listpostapproval'),
    path('publishpost/<int:post_pk>',views.PublishPostView.as_view(),name='publishpost'),
    path('deletepost/delete/<int:pk>',views.DiscardDraft.as_view(),name='deletepost'),
    path('unpublishpost/unpublish/<int:pk>',views.UnpublishPost.as_view(),name='unpublishpost'),

    path('image/new/<int:post_pk>',views.CreatePostImage.as_view(),name='addpostimage'),

]

postapp/models.py
from django.db import models
from django.contrib.auth.models import User
from autoslug import AutoSlugField
from django.utils import timezone
from classapp.models import Category, Tag
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.PROTECT)
    parent = models.ForeignKey("self",null=True,blank=True,on_delete=models.SET_NULL)
# remove blank = True "or not" from parent_id as per implementing logic
    title = models.CharField(max_length=96)
    summary = models.TextField(blank=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

class PostMeta(models.Model):
    post = models.OneToOneField(Post,on_delete=models.CASCADE)
    key = models.CharField(max_length=100,blank=True)
    content = models.TextField(max_length=255,blank=True)
    def __str__(self):
        return self.key

class PostImage(models.Model):
    post = models.ForeignKey(Post, related_name="postimage", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_pictures',blank=True)
    image_caption = models.CharField(max_length=128,blank=True)
    def __str__(self):
        return self.image_caption

class Approval(models.TextChoices):
    Pending = 'PENDING', _('Pending')
    Disapproved = 'DISAPPROVED', _('Disapproved')
    Approved = 'APPROVED', _('Approved')
    
class PublishedPost(models.Model):
    post = models.OneToOneField(Post, related_name='publishedpost', on_delete=models.PROTECT)
    meta_title = models.CharField(max_length=96,blank=True)
    approval = models.CharField(max_length=11, choices=Approval.choices,default=Approval.Pending)
    approver = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    is_published = models.BooleanField(default=True)
    is_archived = models.BooleanField(default=False)
    published_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    slug = AutoSlugField(unique=True, populate_from="post", unique_with='published_on')
    def __str__(self):
        return self.post.title

class FeaturedPost(models.Model):
    ppost = models.OneToOneField(PublishedPost, on_delete=models.CASCADE,related_name="featured")
    featured = models.BooleanField(default=False)
    added_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.ppost.post.title

class Relevance(models.IntegerChoices):
    MOST = 5, "Most Relevant"
    SOMEWHATMORE = 4, "Somewhat More Relevant"
    SOMEWHAT = 3, "Somewhat Relevant"
    SOMEWHATLESS = 2, "Somewhat Less Relevant"
    LEAST = 1, "Least Relevant"

class PostCategory(models.Model):
    ppost = models.OneToOneField(PublishedPost, on_delete=models.CASCADE,related_name='postcategory')
    category = models.ForeignKey(Category,on_delete=models.CASCADE, blank=True, related_name='postcategory')
    category_relevance = models.PositiveSmallIntegerField(
        choices=Relevance.choices,
        default=Relevance.SOMEWHAT
        )
    def __str__(self):
        return self.category.__str__()


class PostTag(models.Model):
    ppost = models.ForeignKey(PublishedPost,on_delete=models.CASCADE,related_name='posttag')
    tag = models.ForeignKey(Tag,on_delete=models.CASCADE,related_name="posttag")
    tag_relevance = models.PositiveSmallIntegerField(
        choices=Relevance.choices,
        default=Relevance.SOMEWHAT
    )
    class Meta:
        unique_together = ['ppost','tag']
    def __str__(self):
        return self.tag.__str__()

postapp/forms.py
from django import forms
from postapp.models import Post, PostCategory, PostTag, PostImage
from classapp.models import Category, Tag
from django.core.exceptions import ObjectDoesNotExist
import re


Approval = [
    ("APPROVED","Approve"),("DISAPPROVED","Disapprove")
]

class PostImageForm(forms.ModelForm):
    class Meta:
        model=PostImage
        fields=('image','image_caption')

class PostApprovalForm(forms.Form):
    approval = forms.ChoiceField(choices=Approval, widget=forms.RadioSelect)
    feature = forms.BooleanField(label='Feature this post',required=False)

class PostCategoryForm(forms.ModelForm):
    class Meta:
        model=PostCategory
        fields=('category',)
        widgets = {'category':forms.Select(),}

class TagForm(forms.Form):
    tags = forms.CharField()
    
    def CreateTagFromTextInput(self, obj, post):
        tags = self.cleaned_data['tags']
        list1 = re.split(r'[,\s][\s|\n]*',tags)
        form_tag_list = list(filter(None,list1))
        
        post_tag_objects=[]
        for newtag in form_tag_list:
            try:
                tag = Tag.objects.get(title__lower=newtag)
            except ObjectDoesNotExist:
                tag = Tag(author=obj.request.user,title=newtag,description="First appeared in post: "+str(post.title))
                tag.save()
                post_tag_objects.append(tag)
            else:
                post_tag_objects.append(tag)
        return post_tag_objects

class PublishPostForm(forms.Form):
    post_category = forms.ModelChoiceField(label='Category',queryset=Category.objects.all(),empty_label="--Select Category--",required=True)
    post_tags = forms.ModelMultipleChoiceField(
        queryset = Tag.objects.all(), 
        widget = forms.CheckboxSelectMultiple(),
    )


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','summary','content')
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'summary':forms.TextInput(attrs={'class':'form-control'}),
            'content':forms.TextInput(attrs={'class':'form-control'}),
        }

class PostEditForm(forms.ModelForm):
    # post_category = forms.ModelChoiceField(label='Category',queryset=Category.objects.all(),empty_label="--Select Category--",required=False)
    class Meta:
        model=Post
        fields=('title','summary','content')

siteapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, FormView, DetailView
from postapp.models import PublishedPost, FeaturedPost, Approval
from commentapp.models import Commenter, Comment
from commentapp.forms import CommenterForm, CommentForm
from classapp.models import Category
from siteapp.forms import CommentForm
# from dashboard.views import AjaxableResponseMixin
# Create your views here.

class MenuContextDataMixin(object):
  """
  Mixing to add a persistant menu on the page.
  This mixin must be used on any view which renders menu
  """
  def get_context_data(self, **kwargs):
    context = super(MenuContextDataMixin,self).get_context_data(**kwargs)
    categories_main = Category.objects.all()[:3]
    categories_more = Category.objects.all()[3:]
    context['categories_main'] = categories_main
    context['categories_more'] = categories_more
    return context


class RelatedPostMixin(object):
  """
  Mixing to add a related posts to page.
  This mixin must be used on views used to display single post objects.
  """
  def get_context_data(self,**kwargs):
    ppost = kwargs.pop('ppost')
    related_category = ppost.postcategory.category
    related_tags = ppost.posttag.all()
    tags=[]
    
    for tag in related_tags:
      tags.append(tag.tag)
    
    related_post = PublishedPost.objects.filter(approval=Approval.Approved,postcategory__category=related_category).exclude(id=ppost.id) or PublishedPost.objects.filter(approval=Approval.Approved,posttag__tag__in=tags).exclude(id=ppost.id)
    
    context = super(RelatedPostMixin,self).get_context_data(**kwargs)
    context['related_posts'] = related_post
    return context


class HomePage(MenuContextDataMixin, ListView):
  model = PublishedPost
  template_name = 'siteapp/homepage.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    fposts = FeaturedPost.objects.filter(featured=True).order_by('-updated_on')[:2]
    fposts_ids = fposts.values_list('ppost_id', flat=True)
    pposts = PublishedPost.objects.filter(approval=Approval.Approved).order_by('-published_on').exclude(id__in=fposts_ids)
    if fposts or pposts:  
      context['featuredPosts'] = fposts
      context['PublishedPosts'] = pposts
    else: 
      context['undercontruction'] = True
    return context

  # def get_queryset(self):
  #   return PublishedPost.objects.filter(approval="APPROVED")

class PostView(MenuContextDataMixin, RelatedPostMixin, FormView):
  form_class = CommentForm
  template_name = 'siteapp/postview.html'
  
  def get_context_data(self, **kwargs):
    ppost = get_object_or_404(PublishedPost,approval=Approval.Approved, slug=self.kwargs['slug'])
    kwargs['ppost'] = ppost
    context = super().get_context_data(**kwargs)

    context['publishedpost'] = ppost
    if ppost.Comments:
      context['comments']=ppost.Comments.filter(approval=Approval.Approved)
    return context
  
  def form_valid(self, form):
    comment_content = form.cleaned_data['comment_content']
    commenter_name = form.cleaned_data['commenter_name']
    commenter_email = form.cleaned_data['commenter_email']

    post = PublishedPost.objects.get(slug=self.kwargs['slug'])
    commenter, created = Commenter.objects.update_or_create(email=commenter_email,defaults={'name':commenter_name})
    comment = Comment(content=comment_content,post=post, commenter=commenter)
    comment.save()
    
    return super().form_valid(form)

  def get_success_url(self,**kwargs):
    return reverse_lazy('siteapp:postview', kwargs={'slug':self.kwargs['slug']})

postapp/templates/postapp/editpost.html
{% extends 'postapp/post_base.html' %}
{% load static %}

{% block windowtitle %}
New Draft
{% endblock windowtitle %}
  
  {% block apptitle %}
  New Draft
  {% endblock apptitle %}

  {% block appview %}
    <div class="h-full">
      <form method="POST" class="h-full">
        {% csrf_token %}
        
        <div class="flex flex-col px-2 pb-2 space-y-4 h-full">
          <div class="flex flex-row border-b -mx-2">
            <button id="id_savepost" name="save" type="submit" class="flex flex-row items-center gap-1 px-4 py-2 hover:bg-blue-50">
              <svg class="fill-stone-600 w-[10px]" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
              viewBox="0 0 49 49" xml:space="preserve">
                <g>
                  <rect x="27.5" y="5" width="6" height="10"/>
                  <path d="M39.914,0H0.5v49h48V8.586L39.914,0z M10.5,2h26v16h-26V2z M39.5,47h-31V26h31V47z"/>
                  <path d="M13.5,32h7c0.553,0,1-0.447,1-1s-0.447-1-1-1h-7c-0.553,0-1,0.447-1,1S12.947,32,13.5,32z"/>
                  <path d="M13.5,36h10c0.553,0,1-0.447,1-1s-0.447-1-1-1h-10c-0.553,0-1,0.447-1,1S12.947,36,13.5,36z"/>
                  <path d="M26.5,36c0.27,0,0.52-0.11,0.71-0.29c0.18-0.19,0.29-0.45,0.29-0.71s-0.11-0.521-0.29-0.71c-0.37-0.37-1.04-0.37-1.41,0
                    c-0.19,0.189-0.3,0.439-0.3,0.71c0,0.27,0.109,0.52,0.29,0.71C25.979,35.89,26.229,36,26.5,36z"/>
                </g>
              </svg>
              <span class="text-sm font-bold text-stone-600 align-bottom">Save</span>
            </button>
            <button name="Publish" type="submit" class="flex flex-row items-center gap-1 px-4 py-2 hover:bg-blue-50">
              <span><svg class="fill-stone-600 w-[10px]" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                  viewBox="0 0 374.116 374.116" xml:space="preserve">
                <g>
                  <path d="M344.058,207.506c-16.568,0-30,13.432-30,30v76.609h-254v-76.609c0-16.568-13.432-30-30-30c-16.568,0-30,13.432-30,30
                    v106.609c0,16.568,13.432,30,30,30h314c16.568,0,30-13.432,30-30V237.506C374.058,220.938,360.626,207.506,344.058,207.506z"/>
                  <path d="M123.57,135.915l33.488-33.488v111.775c0,16.568,13.432,30,30,30c16.568,0,30-13.432,30-30V102.426l33.488,33.488
                    c5.857,5.858,13.535,8.787,21.213,8.787c7.678,0,15.355-2.929,21.213-8.787c11.716-11.716,11.716-30.71,0-42.426L208.271,8.788
                    c-11.715-11.717-30.711-11.717-42.426,0L81.144,93.489c-11.716,11.716-11.716,30.71,0,42.426
                    C92.859,147.631,111.855,147.631,123.57,135.915z"/>
                </g>
              </svg>
              </span>
              <span class="text-sm font-bold text-stone-600 align-bottom">Publish</span></button>
            <a href="{% url 'postapp:deletepost' post.pk %}" class="flex flex-row ml-auto items-center gap-1 px-4 py-2 hover:bg-red-50">
              <svg class="fill-red-600 w-[12px]" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                viewBox="0 0 461.363 461.363"
                xml:space="preserve">
                <g>
                  <polygon points="95.088,461.363 366.276,461.363 389.653,105.984 71.71,105.984 		"/>
                  <path d="M279.192,0h-97.02L71.71,23.557v50.83h317.943v-50.83L279.192,0z M301.683,47.871h-142V26.516h142V47.871z"/>
                </g>
              </svg>
              <span class="text-sm font-bold text-red-600 align-bottom">Delete</span></a>
          </div>
          <div class="flex flex-col xl:flex-row gap-6 xl:gap-2 h-full">
            <div class="xl:w-3/4 flex flex-col grow space-y-6">
              <div>
                <label class="block text-xs font-bold uppercase text-gray-700" for="{{post_form.title.id_for_label}}">title</label>
                <input class="p-1 w-full block border rounded outline-none border-gray-400 focus:outline-gray-600 outline-1 outline-offset-0 font-ibmplexserif font-bold text-md" id="{{form.title.auto_id}}" name={{form.title.html_name}} maxlength={{form.title.field.max_length}} {% if form.title.field.required %}required{% endif %} value="{{form.title.value}}" type="text"/>
              </div>
              <div>
                <label class="block text-xs font-bold uppercase text-gray-700" for="{{post_form.summary.id_for_label}}">Summary</label>
                <textarea id="{{form.summary.auto_id}}" name={{form.summary.html_name}} {% if form.summary.field.required %}required{% endif %} rows="5" class="p-1 w-full block border rounded outline-none border-gray-400 focus:outline-gray-600 outline-1 outline-offset-0 font-ibmplexserif" type="text">{{form.summary.value}}</textarea>
              </div>
              <div>
                <label for={{form.content.id_for_label}} class="block text-xs font-bold uppercase text-gray-700">Content</label>
                <textarea id="{{form.content.auto_id}}" name={{form.content.html_name}} {% if form.content.field.required %}required{% endif %} rows="10" class="p-1 w-full block border rounded outline-none border-gray-400 focus:outline-gray-600 outline-1 outline-offset-0 font-ibmplexserif" type="text">{{form.content.value}}</textarea>
              </div>
            </div>
            <div class="xl:w-64 grow shrink-0">
              <div class="flex flex-col h-full p-4 bg-neutral-50 border rounded-md border-neutral-200 space-y-6">
                <div class="">
                  <label for={{postcategoryform.category.id_for_label}} class="block text-xs font-bold uppercase text-gray-700">Category</label>
                    <select class="bg-white p-1 block w-full border border-neutral-200 font-ibmplexserif text-sm" name={{postcategoryform.category.html_name}} id='{{postcategoryform.category.auto_id}}' {% if postcategoryform.category.field.required %}required{% endif %}>
                      {% for cat_val,cat_name in postcategoryform.category.field.choices  %}
                        <option 
                          {% if postcategoryform.category.value == cat_val %} 
                              selected="selected" 
                          {% endif %} 
                              value={{cat_val}}>{{cat_name}}
                        </option>
                      {% endfor %}
                    </select>
                </div>

                <div>
                  <label class="block text-xs font-bold uppercase text-gray-700" for={{tagform.tags.id_for_label}}>Tags</label>
                  <textarea id="{{tagform.tags.auto_id}}" name="{{tagform.tags.html_name}}" rows="6" spellcheck="false" class="resize-none p-1 w-full block border rounded outline-none border-neutral-200 focus:outline-gray-600 outline-1 outline-offset-0 font-ibmplexserif" type="text"></textarea>
                </div>
                {% if post.postimage %}
                <div class="w-full">
                  <img src={{ post.postimage.all.last.image.url }}>
                </div>
                {% endif %}
                <div class="flex flex-row">
                  <button id="id_publishpost" name="publishpost" class="py-2 px-4 text-blue-600 border border-blue-400 hover:bg-blue-50">Publish</button>
                  <a class="text-blue-600 underline ml-auto" href="{% url 'postapp:addpostimage' object.id %}">Add Image</a>
                </div>
              </div>
            </div>

          </div>

        </div>
      </form>
    </div>
  {% endblock appview %}
  {% block pagescripts %}
  <script>
    $(document).ready(function(){
      $("body").on('click','#id_publishpost',function(event){
        const attr_category_required = $("#id_category").attr("required");
        const attr_tags_required = $("#id_tags").attr("required");
        if (typeof attr_category_required == 'undefined' || attr_category_required == false){
          $("#id_category").attr("required",true);
        }
        if (typeof attr_tags_required == 'undefined' || attr_tags_required == false){
          $("#id_tags").attr("required",true);
        }
        
      });
      $("body").on('click','#id_savepost',function(event){
        console.log("Save clicked");
        const attr_category_required = $("#id_category").attr("required");
        const attr_tags_required = $("#id_tags").attr("required");
        if (typeof attr_category_required !== 'undefined' || attr_category_required !== false){
          $("#id_category").removeAttr("required");
        }
        if (typeof attr_tags_required !== 'undefined' || attr_tags_required !== false){
          $("#id_tags").removeAttr("required");
        }
      });
    })
  </script>
  {% endblock pagescripts %}
	{% comment %} <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="sidebar_menu.js"></script> {% endcomment %}

postapp/templates/postapp/list_draft_posts.html
{% extends 'postapp/post_base.html' %}
{% load static %}

{% block windowtitle %}
Draft Posts
{% endblock windowtitle %}

  {% block apptitle %}
  Draft Posts
  {% endblock apptitle %}

  {% block appview %}
  <div class="overflow-x-auto relative border border-stone-200">
    {% if post_list %}
    <table class="w-full text-sm text-left text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="py-3 px-6 min-w-[200px]">Title</th>
          <th scope="col" class="py-3 px-6 min-w-[272px]">Created</th>
          <th scope="col" class="py-3 px-6 min-w-[150px]">Updated</th>
          <th scope="col" class="py-3 px-6 min-w-[154px]">Action</th>
        </tr>
      </thead>
      <tbody class="">
        {% for post in post_list %}
        <tr class="bg-white border-b">
          <th scope="row" class="py-4 px-6 font-medium text-gray-900">
            {% if post.title %}{{post.title}}
            {% else %}<i>No Title</i>{% endif %}  
          </th>
          <td class="py-4 px-6">{{post.created_on}}</td>
          <td class="py-4 px-6">{{post.updated_on}}</td>
          <td class="py-4 px-6">
            <a class="text-green-700 hover:underline" href={% url 'postapp:editpost' post.pk %}>Edit</a> | 
            <a class="text-red-700 hover:underline inline" href={% url 'postapp:deletepost' post.pk %}>Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="text-center my-12">
      <h2 class="text-2xl">No Drafts</h2>
      <p class="">Your drafts will appear here once you start writing</p>
    </div>
    {% endif %}
  </div>
  {% endblock appview %}

postapp/templates/postapp/list_published_posts.html
{% extends 'postapp/post_base.html' %}
{% load static %}

{% block windowtitle %}
Published Posts
{% endblock windowtitle %}

  {% block apptitle %}
  Published Posts
  {% endblock apptitle %}

  {% block appview %}
  <div class="overflow-x-auto relative border border-stone-200">
    {% if publishedpost_list %}
    <table class="w-full text-sm text-left text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="py-3 px-6 min-w-[200px]">Title</th>
          <th scope="col" class="py-3 px-6">Publish Date</th>
          <th scope="col" class="py-3 px-6">Category</th>
          <th scope="col" class="py-3 px-6">Approval</th>
          <th scope="col" class="py-3 px-6">Approver</th>
          <th scope="col" class="py-3 px-6">Action</th>
        </tr>
      </thead>
      <tbody class="">
        {% for ppost in publishedpost_list %}
        <tr class="bg-white border-b">
          <th scope="row" class="py-4 px-6 font-medium text-gray-900">
            {{ppost.post.title}}</th>
          <td class="py-4 px-6">{{ppost.published_on|date:'d M, Y'}}</td>
          <td class="py-4 px-6">{{ppost.postcategory.category.title}}</td>
          {% if ppost.approval == "APPROVED" %}
            <td class="text-green-700 py-4 px-6">Approved</td>
          {% elif ppost.approval == "PENDING" %}
            <td class="text-amber-500 py-4 px-6">Pending</td>
          {% elif ppost.approval == "DISAPPROVED" %}
            <td class="text-red-700 py-4 px-6">Rejected</td>
          {% endif %}
          {% if ppost.approver %}
            <td class="py-4 px-6">
              {{ppost.approver}}</td>
          {% else %}
            <td class="py-4 px-6"> - </td>
          {% endif %}
          <td class="py-4 px-6">
            <a href={% url 'postapp:publishedpost' ppost.pk %} class="text-blue-700 hover:underline">View</a>
            {% if ppost.approval != "APPROVED" %}
              | <a href={% url 'postapp:unpublishpost' ppost.pk %} class="text-red-700 hover:underline">Unpublish</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="text-center my-12">
      <h2 class="text-2xl">No Published posts</h2>
      <p class="">Your published posts will appear here once you start publishing</p>
    </div>
    {% endif %}
  </div>
  {% endblock appview %}

postapp/templates/postapp/newpost.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block windowtitle %}
    <title>New Post | Dashboard</title>
{% endblock windowtitle %}

{% block pagecontent %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
          <div class="my-4">
            <h2 id="id_page_heading">New Post</h2>
          </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <form method="post" id="id_post_form" class="needs-validation" novalidate>
              {% csrf_token %}
              <div class ="form-canvas p-4 shadow-sm">
                <div class="my-2">
                  <input type="hidden" id="id_post_content_url" name="post_content_url" post_save_url="{% url 'postapp:newpost' %}">
                  <input type="hidden" id="id_loginstatusquery" name="loginstatusquery" loginstatusquery_url="{% url 'useraccounts:loginstatusquery' %}">
                  <div class="title-input">
                    <label class="fw-semibold" for={{post_form.title.id_for_label}}>Title</label>
                    <input class="form-control post_required" name={{post_form.title.html_name}} id={{post_form.title.auto_id}} maxlength={{post_form.title.field.max_length}} type="text" {% if post_form.title.field.required %}required{% endif %}>
                    <div class="valid-feedback">Looks good!</div>
                    <div class="invalid-feedback">Opps! You forgot the title</div>
                  </div>
                  <div class="summary-input mt-4">
                    <label class="fw-semibold" for={{post_form.summary.id_for_label}}>Summary</label>
                    <textarea class="form-control" name={{post_form.summary.html_name}} id='{{post_form.summary.auto_id}}' {% if post_form.summary.field.required %} required {% endif %}></textarea>
                    <div class="valid-feedback">This can be empty, your choice</div>
                  </div>
                  <div class="content-input mt-4">
                    <label class="fw-semibold" for={{post_form.content.id_for_label}}>Content</label>
                    <textarea class="form-control post_required" name={{post_form.content.html_name}} id={{post_form.content.auto_id}} rows="8" {% if post_form.content.field.required %}required{% endif %}></textarea>
                    <div class="valid-feedback">Looks good!</div>
                    <div class="invalid-feedback">You need to write something in content</div>
                  </div>
                </div>
              </div>
              <div class="d-grid gap-2 d-md-block mt-4">
                <button name="Save" class="btn py-3 px-4 btn-primary me-2" type="submit">Save Draft</button>
              </div>
            </form>
        </div>
    </div>
</div>
<div class="" id="id_modal_placeholder"></div>
{% endblock pagecontent %}

{% block page_scripts %}
  <script type="text/javascript" src="{% static 'postapp\js\post_save_0.js' %}"></script>
  <script type="text/javascript" src="{% static 'postapp\js\bs_form_validator.js' %}"></script>
  <script type="text/javascript" src="{% static 'useraccounts\js\loginstatusquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'useraccounts\js\login_modal.js' %}"></script>
{% endblock page_scripts %}