adminapp/urls.py
from django.urls import path
from adminapp import views
from classapp.views import CategoryList, CreateCategoryView, EditCategoryView, DeleteCategoryView
app_name = 'adminapp'
urlpatterns=[
  path('post/listpendingpost',views.ListPendingPost.as_view(),name='listpendingpost'),
  path('post/listapprovedpost',views.ListApprovedPost.as_view(),name='listapprovedpost'),
  path('post/listdisapprovedpost',views.ListDisapprovedPost.as_view(),name='listdisapprovedpost'),

  path('comment/list/<str:approval>',views.ListComment.as_view(),name='listcomment'),

  path('post/postapproval/<int:pk>',views.PostApproval.as_view(),name='postapproval'),

  path('categories/all',CategoryList.as_view(),name='categories'),
  path('categories/new',CreateCategoryView.as_view(),name='createcategory'),
  path('categories/edit/<slug:slug>',EditCategoryView.as_view(),name='editcategory'),
  path('categories/<slug:slug>/delete',DeleteCategoryView.as_view(),name='deletecategory'),  
]

cmsapp/urls.py
from django.urls import path
from cmsapp import views

app_name = 'cmsapp'
urlpatterns=[
  path('home/',views.CMSHome.as_view(),name='cmshome'),
]

inksynk/urls.py
from django.contrib import admin
from django.urls import path, include

# for static files during deployment
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('site/admin', admin.site.urls),
    path('',include("siteapp.urls")),
    path('cms/',include("cmsapp.urls")),
    path('cms/user/',include("userapp.urls")),
    path('cms/post/',include("postapp.urls")),
    # path('cms/dashboard/',include("dashboard.urls")),
    path('cms/class/',include("classapp.urls")),
    path('cms/comments/',include("commentapp.urls")),
    path('cms/admin/',include("adminapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postapp/urls.py
from django.urls import path
from postapp import views

app_name = 'postapp'
urlpatterns = [
    path('postapproval/<int:pk>', views.PostApproval.as_view(), name='postapproval'),
    path('newpost',views.CreatePostView.as_view(),name='newpost'),
    path('editpost/<int:pk>',views.EditPostView.as_view(),name='editpost'),
    path('drafts',views.ListDraftPosts.as_view(),name='draftposts'),
    
    path('published',views.ListPublishedPosts.as_view(),name='publishedposts'),
    path('published/<int:pk>',views.PublishedPostView.as_view(),name='publishedpost'),
    
    path('approved',views.ListApprovedPosts.as_view(),name='approvedposts'),
    path('listpostapproval',views.ListPostApproval.as_view(),name='listpostapproval'),
    path('publishpost/<int:post_pk>',views.PublishPostView.as_view(),name='publishpost'),
    path('deletepost/delete/<int:pk>',views.DiscardDraft.as_view(),name='deletepost'),
    path('unpublishpost/unpublish/<int:pk>',views.UnpublishPost.as_view(),name='unpublishpost'),

    path('image/new/<int:post_pk>',views.CreatePostImage.as_view(),name='addpostimage'),

]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from commentapp.models import Comment


Approval = [
    ("APPROVED","Approve"),("DISAPPROVED","Disapprove")
]

class PostApprovalForm(forms.Form):
    approval = forms.ChoiceField(choices=Approval, widget=forms.RadioSelect)
    feature = forms.BooleanField(label='Feature this post',required=False)

class CommentApprovalForm(forms.Form):
    approval = forms.ChoiceField(choices=Approval,widget=forms.Select,)
    comment_approval = forms.BooleanField(widget=forms.CheckboxInput)

adminapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from postapp.models import PublishedPost, FeaturedPost, Approval
from commentapp.models import Comment, Commenter
from adminapp.forms import PostApprovalForm, CommentApprovalForm
from django.utils.translation import gettext_lazy as _
# Create your views here.

class ListComment(LoginRequiredMixin, UserPassesTestMixin, FormView):
  form_class = CommentApprovalForm
  template_name = 'adminapp/list_comment.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    approval = self.kwargs['approval']
    if approval=="approved":
      approval = Approval.Approved
    elif approval == "pending":
      approval = Approval.Pending
    elif approval == "disapproved":
      approval = Approval.Disapproved
    else:
      approval = None
    if approval:
      context['comment_list'] = Comment.objects.filter(approval=approval).order_by('-updated_on')
    else:
      context['comment_list'] = Comment.objects.all().order_by('-created_on')
    return context

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test

  def form_valid(self,form):
    approval = form.cleaned_data['approval']
    item_list = self.request.POST.getlist('comment_approval')
    if approval=="APPROVED":
      approval=Approval.Approved
    elif approval=="DISAPPROVED":
      approval=Approval.Disapproved
    else:
      return super().form_invalid(form)
    print(item_list)
    comment_approval_list = Comment.objects.filter(id__in=item_list)
    for comment in comment_approval_list:
      comment.approval = approval
      comment.save()
      print("Comment is: "+str(comment.approval))
    return super().form_invalid(form)

class ListApprovedPost(LoginRequiredMixin, ListView, UserPassesTestMixin):
  model=PublishedPost
  template_name = 'adminapp/list_approved_post.html'
  context_object_name = 'approvedpost_list'

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test

  def get_queryset(self):
    approvedpost_list = PublishedPost.objects.filter(is_published=True,approval=Approval.Approved)
    return approvedpost_list

class ListDisapprovedPost(LoginRequiredMixin, ListView, UserPassesTestMixin):
  model=PublishedPost
  template_name = 'adminapp/list_disapproved_post.html'
  context_object_name = 'post_list'

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test

  def get_queryset(self):
    disapprovedpost_list = PublishedPost.objects.filter(is_published=True,approval=Approval.Disapproved)
    return disapprovedpost_list

class ListPendingPost(LoginRequiredMixin, ListView, UserPassesTestMixin):
  model = PublishedPost
  template_name = 'adminapp/list_pending_post.html'
  context_object_name = 'pendingpost_list'

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test

  def get_queryset(self):
    pendingpost_list = PublishedPost.objects.filter(is_published=True,approval=Approval.Pending)
    return pendingpost_list
  

class PostApproval(LoginRequiredMixin, UserPassesTestMixin, FormView):
  form_class = PostApprovalForm
  template_name='adminapp/post_approval.html'
  success_url = reverse_lazy('adminapp:listapprovedpost')
  # success_url = reverse_lazy('postapp:publishedposts')

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    ppost = get_object_or_404(PublishedPost, pk=self.kwargs['pk'])
    context['ppost'] = ppost
    if context['ppost'].approval != 'PENDING':
      context['form']['approval'].initial=context['ppost'].approval
      print(type(context['form']['approval'].initial))
      try:
        if ppost.featured:
          pass
      except:
        print("Not Featured")

      else:
        if ppost.featured.featured==True:
          context['form']['feature'].initial=True
    # print("Before approval value in db: " + context['ppost'].approval)
    return context

  def form_valid(self,form):
    approval = form.cleaned_data['approval']
    feature = form.cleaned_data['feature']
    ppost = get_object_or_404(PublishedPost, pk=self.kwargs['pk'])
    is_featured=False
    try:
      fpost = ppost.featured
    except:
      print("Not Featured")
      fpost = False
    else:
      if fpost and fpost.featured:
        is_featured=True
      
      # print("Approval value returned: "+ approval)
    if approval==Approval.Approved:
      print("Approved (form)")
      if ppost.approval != Approval.Approved:
        ppost.approval = Approval.Approved
        ppost.approver = self.request.user
        ppost.save()
      if feature == True and not(is_featured):
        if not(fpost):
            fpost, created = FeaturedPost.objects.get_or_create(ppost=ppost)        
        fpost.featured=True
        fpost.save()
        print("Featured Post Set")
      elif feature == False and is_featured:
        fpost.featured = False
        fpost.save()

        # print("approval in db: " + ppost.approval)
      
    elif approval == Approval.Disapproved:
        if fpost:
          fpost.featured=False
          fpost.save()
        if ppost.approval != Approval.Disapproved:
          ppost.approval = Approval.Disapproved
          ppost.approver = self.request.user
          ppost.save()
        print("approval in db: " + ppost.approval)
    else:
      return super().form_invalid(form)
    return super().form_valid(form)

  def get_success_url(self):
    response = super().get_success_url()
    if Approval.Disapproved in self.request.POST['approval']:
      print("post is disapproved")
      response = reverse_lazy('adminapp:listdisapprovedpost')
    return response

adminapp/templates/adminapp/admin_base.html
{% extends 'cmsapp/base.html' %}
{% load static %}
{% block pagecontent %}

  <div class="p-2 bg-stone-200 rounded-t-md border border-stone-200">
    <h1 class="text-md uppercase font-bold text-stone-600">
    {% block apptitle %}

    {% endblock apptitle %}
    </h1>
  </div>  
  
  {% include "adminapp/snippets/adminapp_main_menu.html" %}
  {% block submenu %}
  
  {% endblock submenu %}
  <div class="overflow-x-auto relative border border-stone-200">
  {% block appview %}

  {% endblock appview %}
  </div>
{% endblock pagecontent %}

adminapp/templates/adminapp/admin_category_base.html
{% extends 'adminapp/admin_base.html' %}
{% load static %}
{% block pagecontents %}
<div class="p-2 bg-stone-200 rounded-t-md border border-stone-200">
  <h1 class="text-md uppercase font-bold text-stone-600">
  {% block apptitle %}
    Administration > Categories
  {% endblock apptitle %}
  </h1>
</div> 
{% block submenu %}
  {% include "adminapp/snippets/adminapp_categories_menu.html" %}
{% endblock submenu %}

<div class="overflow-x-auto relative border-x border-b border-stone-200">
  {% block appview %}
  
  {% endblock appview %}
</div>
{% endblock pagecontents %}

adminapp/templates/adminapp/category_confirm_delete.html
{% extends 'adminapp/admin_category_base.html' %}
{% load static %}

{% block windowtitle %}
  Delete Category
{% endblock windowtitle %}

  {% block apptitle %}
    Delete Category
  {% endblock apptitle %}

  {% block appview %}
  <div class="border border-stone-200 h-full">
    <form method="POST">{% csrf_token %}
      <div class="flex flex-col text-center gap-4 px-4 py-10 h-full">
        <p class="font-montserrat text-xl">
          Are you sure you want to delete this category?
        </p>
        <p class="font-ibmplexserif text-lg">
          {% if category.title %}
            {{category.title}}
          {% else %}
            No Title
          {% endif %}
        </p>
        {{form}}
        <div class="">
          <button class="rounded text-white px-6 py-2 bg-red-700" type="submit" value="Confirm">Confirm</button>
          <a href="{% url 'adminapp:categories' %}" class="rounded text-white px-6 py-3 bg-gray-600 hover:bg-gray-500">No, Take me back</a>
        </div>
      </div>
    </form>
  </div>
  {% endblock appview %}

adminapp/templates/adminapp/list_approved_post.html
{% extends 'adminapp/admin_post_base.html' %}
{% block windowtitle %}
Approved Posts
{% endblock windowtitle %}

  {% block appview %}
  {% if approvedpost_list %}
  <table class="w-full text-sm text-left text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="py-3 px-6 min-w-[200px]">Title</th>
        <th scope="col" class="py-3 px-6">Author</th>
        <th scope="col" class="py-3 px-6">Publish Date</th>
        <th scope="col" class="py-3 px-6">Category</th>
        <th scope="col" class="py-3 px-6">Approver</th>
        <th scope="col" class="py-3 px-6">Quick Action</th>
      </tr>
    </thead>
    <tbody class="">
      {% for apost in approvedpost_list %}
      <tr class="bg-white border-b">
        <th scope="row" class="py-4 px-6 font-medium text-gray-900">
          {{apost.post.title}}</th>
        <td class="py-4 px-6">{{apost.post.author}}</td>
        <td class="py-4 px-6">{{apost.published_on|date:'d M, Y'}}</td>
        <td class="py-4 px-6">{{apost.postcategory.category.title}}</td>
        {% if apost.approver %}
          <td class="text-blue-700 py-4 px-6">{{apost.approver}}</td>
        {% endif %}
        <td class="py-4 px-6">
          <a href="#" class="text-amber-600 hover:underline">Archive</a> | 
          <a href="{% url 'adminapp:postapproval' apost.pk  %}" class="text-red-700 hover:underline">Review</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div class="text-center my-12">
    <h2 class="text-2xl">No Approved Posts</h2>
    <p class="">Posts will appear here once they are approved</p>
  </div>
  {% endif %}
  
  {% endblock appview %}

adminapp/templates/adminapp/list_category.html
{% extends 'adminapp/admin_category_base.html' %}
{% load cmsClassTags %}
{% block windowtitle %}
Categories
{% endblock windowtitle %}

  {% block appview %}
    {% if category_list %}
      <div class="p-2 flex flex-col space-y-1">
        {% for category in category_list %}
          <div class="flex flex-row bg-stone-100 rounded">
            <div class="w-1/3 py-4 px-6">
            
              <div class="font-bold text-gray-900">{{category.title}}</div>
              <div class="text-gray-500 mt-2 text-xs"><span class="text-blue-600 font-bold">                
                {% with postcount=category.postcategory|catUserPostCount:user %}
                  {{ postcount }} post{{ postcount|pluralize }}
                {% endwith %} 
                </span>
              </div>
            </div>
            <div class="w-1/3 py-4 px-6">
              <div class="">{{category.description}}</div>
              <div class="text-gray-500 mt-2 text-xs">Created on <span class="text-blue-600 font-bold">{{category.created_on|date:'d M, Y'}}</span>
              by <span class="text-blue-600 font-bold">{{category.author}}</span>
              </div>
            </div>
            <div class="w-1/3 py-4 px-6">
              <div class="flex flex-row gap-2 text-sm">
                <a href={% url 'adminapp:editcategory' category.slug %} class="ml-auto text-blue-600 underline">Edit</a>
                <a href="{% url 'adminapp:deletecategory' category.slug %}" class="text-red-600 underline">Delete</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
    <div class="text-center my-12">
      <h2 class="text-2xl">Opps!</h2>
      <p class="">No categories created...</p>
    </div>
    {% endif %}

  {% endblock appview %}

adminapp/templates/adminapp/list_disapproved_post.html
{% extends 'adminapp/admin_post_base.html' %}
{% block windowtitle %}
Approved Posts
{% endblock windowtitle %}

  {% block appview %}
  {% if post_list %}
  <table class="w-full text-sm text-left text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="py-3 px-6 min-w-[200px]">Title</th>
        <th scope="col" class="py-3 px-6">Author</th>
        <th scope="col" class="py-3 px-6">Publish Date</th>
        <th scope="col" class="py-3 px-6">Category</th>
        <th scope="col" class="py-3 px-6">Approver</th>
        <th scope="col" class="py-3 px-6">Quick Action</th>
      </tr>
    </thead>
    <tbody class="">
      {% for dpost in post_list %}
      <tr class="bg-white border-b">
        <th scope="row" class="py-4 px-6 font-medium text-gray-900">
          {{dpost.post.title}}</th>
        <td class="py-4 px-6">{{dpost.post.author}}</td>
        <td class="py-4 px-6">{{dpost.published_on|date:'d M, Y'}}</td>
        <td class="py-4 px-6">{{dpost.postcategory.category.title}}</td>
        {% if dpost.approver %}
          <td class="text-blue-700 py-4 px-6">{{dpost.approver}}</td>
        {% endif %}
        <td class="py-4 px-6">
          <a href="#" class="text-amber-600 hover:underline">Archive</a> | 
          <a href="{% url 'adminapp:postapproval' dpost.pk  %}" class="text-blue-700 hover:underline">Review</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div class="text-center my-12">
    <h2 class="text-2xl">No Disapproved Posts</h2>
    <p class="">Disapproved posts will appear here</p>
  </div>
  {% endif %}
  
  {% endblock appview %}

adminapp/templates/adminapp/list_pending_post.html
{% extends 'adminapp/admin_post_base.html' %}
{% block windowtitle %}
Pending Approval
{% endblock windowtitle %}

  {% block appview %}
  {% if pendingpost_list %}
  <table class="w-full text-sm text-left text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="py-3 px-6 min-w-[200px]">Title</th>
        <th scope="col" class="py-3 px-6">Author</th>
        <th scope="col" class="py-3 px-6">Publish Date</th>
        <th scope="col" class="py-3 px-6">Category</th>
        <th scope="col" class="py-3 px-6">Quick Action</th>
      </tr>
    </thead>
    <tbody class="">
      {% for ppost in pendingpost_list %}
      <tr class="bg-white border-b">
        <th scope="row" class="py-4 px-6 font-medium text-gray-900">
          {{ppost.post.title}}</th>
        <td class="py-4 px-6">{{ppost.post.author}}</td>
        <td class="py-4 px-6">{{ppost.published_on|date:'d M, Y'}}</td>
        <td class="py-4 px-6">{{ppost.postcategory.category.title}}</td>
        <td class="py-4 px-6">
          <a href="{% url 'adminapp:postapproval' ppost.pk %}" class="text-blue-700 hover:underline">View</a>
          {% if ppost.approval != "APPROVED" %}
            <a href="#" class="text-green-700 hover:underline">Approve</a> | 
            <a href="#" class="text-red-700 hover:underline">Disapprove</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div class="text-center my-12">
    <h2 class="text-2xl">All done!</h2>
    <p class="">You currently do not have any pending approvals</p>
  </div>
  {% endif %}
  
  {% endblock appview %}

adminapp/templates/adminapp/post_approval.html
{% extends 'adminapp/admin_base.html' %}
{% load static %}

{% block windowtitle %}
Administration | Post Approval
{% endblock windowtitle %}

  {% block apptitle %}
  Administration
  {% endblock apptitle %}
  {% block appview %}
  <div class="h-full">
    <div class="flex flex-col px-2 pb-2 space-y-4 h-full">
      
      <div class="flex flex-col pt-4 xl:flex-row gap-6 xl:gap-2 h-full">
        <div class="xl:w-3/4 flex flex-col grow items-center h-full">
          <div class="space-y-6 md:max-w-[90%] md:min-w-[80%] xl:min-w-[70%] 2xl:max-w-[60%] p-4 border border-gray-300 shadow min-h-[99%]">
            {% if ppost.post.postimage %}
            <div>
              <img src={{ppost.post.postimage.all.last.image.url}} />
            </div>
            {% endif %}
            <div>
              <h2 class="text-xl font-bold text-gray-800 font-serif">{{ppost.post.title}}</h2>
            </div>
            <div>
              <p class="text-md text-gray-800 font-serif">
                {{ppost.post.summary}}
              </p>
            </div>
            <div>
              <p class="text-md text-gray-800 font-serif">
                {{ppost.post.content}}
              </p>
            </div>

          </div>
        </div>
        <div class="space-y-4 xl:w-64 grow shrink-0 flex flex-col overflow-y-auto">

          <div>

            <div class="p-2 bg-blue-100">
              Post Approval
            </div>
            <form method="POST">{% csrf_token %}
              
              <div class="p-4 space-y-4 bg-neutral-50 border border-neutral-200">
                <ul class="flex flex-row gap-2 flex-wrap">
                  {% for e in form.approval.field.choices %}
                      
                      <li>
                        <input type="radio" id="{{form.approval.auto_id}}_{{forloop.counter0}}" value="{{e.0}}" name="{{form.approval.name}}" {% if form.approval.initial == e.0 %} checked='checked' {% endif %}
                         class="hidden peer">
                        <label for="{{form.approval.auto_id}}_{{forloop.counter0}}" class="inline-flex p-2 w-full text-gray-700 bg-inherit rounded-full cursor-pointer peer-checked:bg-sky-400 hover:text-sky-400  peer-checked:text-white hover:bg-sky-100">
                            <div class="block w-full text-sm">{{e.1}}</div>
                        </label>
                        {{e.id_for_label}}
                      </li>

                  {% endfor %}
                </ul>
                
                <div class="inline-flex">
                  <input type="checkbox" id="{{form.feature.auto_id}}" name="{{form.feature.name}}" class="hidden peer" {% if form.feature.initial %} checked='checked' {% endif %}>
                  <label for="{{form.feature.id_for_label}}" class="inline-flex p-2 w-full bg-inherit text-gray-700 fill-gray-700 rounded-full cursor-pointer hover:text-emerald-500 hover:fill-emerald-500 hover:bg-emerald-50 peer-checked:fill-white peer-checked:text-white peer-checked:bg-emerald-600">
                    <div class="inline-flex gap-1 w-full text-sm">
                      <svg class="bg-inherit fill-inherit" 
                        width="15px" height="15px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                        viewBox="0 0 329.942 329.942" xml:space="preserve">
                      <path id="XMLID_16_" d="M329.208,126.666c-1.765-5.431-6.459-9.389-12.109-10.209l-95.822-13.922l-42.854-86.837
                        c-2.527-5.12-7.742-8.362-13.451-8.362c-5.71,0-10.925,3.242-13.451,8.362l-42.851,86.836l-95.825,13.922
                        c-5.65,0.821-10.345,4.779-12.109,10.209c-1.764,5.431-0.293,11.392,3.796,15.377l69.339,67.582L57.496,305.07
                        c-0.965,5.628,1.348,11.315,5.967,14.671c2.613,1.899,5.708,2.865,8.818,2.865c2.387,0,4.784-0.569,6.979-1.723l85.711-45.059
                        l85.71,45.059c2.208,1.161,4.626,1.714,7.021,1.723c8.275-0.012,14.979-6.723,14.979-15c0-1.152-0.13-2.275-0.376-3.352
                        l-16.233-94.629l69.339-67.583C329.501,138.057,330.972,132.096,329.208,126.666z"/>
                      </svg>
                      {{form.feature.field.label}}</div>
                  </label>
                </div>
              </div>

              <div class="bg-neutral-100 border border-x-neutral-200 border-b-neutral-200 flex flex-row">
                <button class="flex flex-row items-center gap-1 px-4 py-2" name="Approval" type="submit" value="submit">
                  
                  <svg width="15px" height="15px" class="fill-blue-700" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                  viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve">
                    <g>
                      <g id="spin">
                        <g>
                          <path d="M25.883,6.086l-2.82,2.832C24.953,10.809,26,13.324,26,16c0,5.516-4.484,10-10,10v-2l-4,4l4,4v-2
                            c7.719,0,14-6.281,14-14C30,12.254,28.539,8.734,25.883,6.086z"/>
                          <path d="M20,4l-4-4v2C8.281,2,2,8.281,2,16c0,3.746,1.461,7.266,4.117,9.914l2.82-2.832
                            C7.047,21.191,6,18.676,6,16c0-5.516,4.484-10,10-10v2L20,4z"/>
                        </g>
                      </g>
                    </g>
                    </svg>
                  
                <span class="text-sm font-bold text-blue-600 align-bottom">Apply</span></button>
              </div>
            </form>
            
          </div>

          <div>
            <div class="p-2 bg-neutral-200">
              Post Info
            </div>
            <div class="p-4 space-y-4 bg-neutral-50 border border-neutral-200">
              <div class="text-sm">
                <span class="text-gray-500">Status </span><span class="text-gray-700 ml-2">
                  {% if ppost.is_published %}
                    Published
                  {% else %}
                    Draft
                  {% endif %}
                  </span>
              </div>
  
              <div class="text-sm">
                <span class="text-gray-500">Approval </span><span class="text-gray-700 ml-2">
                  {% if ppost.approval == "PENDING" %}
                    Pending
                  {% elif ppost.approval == "APPROVED" %}
                    Approved
                  {% elif ppost.approval == "DISAPPROVED" %}
                    Disapproved
                  {% endif %}
                  </span>
              </div>
  
              <div class="text-sm">
                <span class="text-gray-500">Category </span><span class="text-gray-700 ml-2">
                  {{ppost.postcategory.category.title}}</span>
              </div>
              <div class="text-sm">
                <span class="text-gray-500">Published on </span><span class="text-gray-700 ml-2">
                  {{ppost.published_on|date:'d M Y'}}</span>
              </div>
              <div class="text-sm flex flex-row flex-wrap gap-2">
                <span class="text-gray-500">Tags</span>
                {% for tag in ppost.posttag.all  %}
                  <span class="text-blue-700">{{tag}}</span>
                  
                {% endfor %}
              </div>
              
            </div>
  
            <div class="bg-neutral-100 border border-x-neutral-200 border-b-neutral-200 flex flex-row">
              <a href="{% url 'postapp:unpublishpost' ppost.pk %}" class="flex flex-row items-center gap-1 px-4 py-2 hover:bg-red-50">
                <svg class="fill-red-600 w-[12px]" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                  viewBox="0 0 461.363 461.363"
                  xml:space="preserve">
                  <g>
                    <polygon points="95.088,461.363 366.276,461.363 389.653,105.984 71.71,105.984 		"/>
                    <path d="M279.192,0h-97.02L71.71,23.557v50.83h317.943v-50.83L279.192,0z M301.683,47.871h-142V26.516h142V47.871z"/>
                  </g>
                </svg>
              <span class="text-sm font-bold text-red-600 align-bottom">Unpublish</span></a>
            </div>
          </div>
          
        </div>

      </div>

    </div>
  </div>
  {% endblock appview %}