adminapp/urls.py
from django.urls import path
from adminapp import views
from classapp.views import CategoryList, CreateCategoryView, EditCategoryView, DeleteCategoryView
app_name = 'adminapp'
urlpatterns=[
  path('post/listpendingpost',views.ListPendingPost.as_view(),name='listpendingpost'),
  path('post/listapprovedpost',views.ListApprovedPost.as_view(),name='listapprovedpost'),
  path('post/listdisapprovedpost',views.ListDisapprovedPost.as_view(),name='listdisapprovedpost'),

  path('comment/list/<str:approval>',views.ListComment.as_view(),name='listcomment'),

  path('post/postapproval/<int:pk>',views.PostApproval.as_view(),name='postapproval'),

  path('categories/all',CategoryList.as_view(),name='categories'),
  path('categories/new',CreateCategoryView.as_view(),name='createcategory'),
  path('categories/edit/<slug:slug>',EditCategoryView.as_view(),name='editcategory'),
  path('categories/<slug:slug>/delete',DeleteCategoryView.as_view(),name='deletecategory'),  
]

cmsapp/urls.py
from django.urls import path
from cmsapp import views

app_name = 'cmsapp'
urlpatterns=[
  path('home/',views.CMSHome.as_view(),name='cmshome'),
]

inksynk/urls.py
from django.contrib import admin
from django.urls import path, include

# for static files during deployment
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('site/admin', admin.site.urls),
    path('',include("siteapp.urls")),
    path('cms/',include("cmsapp.urls")),
    path('cms/user/',include("userapp.urls")),
    path('cms/post/',include("postapp.urls")),
    # path('cms/dashboard/',include("dashboard.urls")),
    path('cms/class/',include("classapp.urls")),
    path('cms/comments/',include("commentapp.urls")),
    path('cms/admin/',include("adminapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from commentapp.models import Comment


Approval = [
    ("APPROVED","Approve"),("DISAPPROVED","Disapprove")
]

class PostApprovalForm(forms.Form):
    approval = forms.ChoiceField(choices=Approval, widget=forms.RadioSelect)
    feature = forms.BooleanField(label='Feature this post',required=False)

class CommentApprovalForm(forms.Form):
    approval = forms.ChoiceField(choices=Approval,widget=forms.Select,)
    comment_approval = forms.BooleanField(widget=forms.CheckboxInput)

adminapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from postapp.models import PublishedPost, FeaturedPost, Approval
from commentapp.models import Comment, Commenter
from adminapp.forms import PostApprovalForm, CommentApprovalForm
from django.utils.translation import gettext_lazy as _
# Create your views here.

class ListComment(LoginRequiredMixin, UserPassesTestMixin, FormView):
  form_class = CommentApprovalForm
  template_name = 'adminapp/list_comment.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    approval = self.kwargs['approval']
    if approval=="approved":
      approval = Approval.Approved
    elif approval == "pending":
      approval = Approval.Pending
    elif approval == "disapproved":
      approval = Approval.Disapproved
    else:
      approval = None
    if approval:
      context['comment_list'] = Comment.objects.filter(approval=approval).order_by('-updated_on')
    else:
      context['comment_list'] = Comment.objects.all().order_by('-created_on')
    return context

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test

  def form_valid(self,form):
    approval = form.cleaned_data['approval']
    item_list = self.request.POST.getlist('comment_approval')
    if approval=="APPROVED":
      approval=Approval.Approved
    elif approval=="DISAPPROVED":
      approval=Approval.Disapproved
    else:
      return super().form_invalid(form)
    print(item_list)
    comment_approval_list = Comment.objects.filter(id__in=item_list)
    for comment in comment_approval_list:
      comment.approval = approval
      comment.save()
      print("Comment is: "+str(comment.approval))
    return super().form_invalid(form)

class ListApprovedPost(LoginRequiredMixin, ListView, UserPassesTestMixin):
  model=PublishedPost
  template_name = 'adminapp/list_approved_post.html'
  context_object_name = 'approvedpost_list'

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test

  def get_queryset(self):
    approvedpost_list = PublishedPost.objects.filter(is_published=True,approval=Approval.Approved)
    return approvedpost_list

class ListDisapprovedPost(LoginRequiredMixin, ListView, UserPassesTestMixin):
  model=PublishedPost
  template_name = 'adminapp/list_disapproved_post.html'
  context_object_name = 'post_list'

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test

  def get_queryset(self):
    disapprovedpost_list = PublishedPost.objects.filter(is_published=True,approval=Approval.Disapproved)
    return disapprovedpost_list

class ListPendingPost(LoginRequiredMixin, ListView, UserPassesTestMixin):
  model = PublishedPost
  template_name = 'adminapp/list_pending_post.html'
  context_object_name = 'pendingpost_list'

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test

  def get_queryset(self):
    pendingpost_list = PublishedPost.objects.filter(is_published=True,approval=Approval.Pending)
    return pendingpost_list
  

class PostApproval(LoginRequiredMixin, UserPassesTestMixin, FormView):
  form_class = PostApprovalForm
  template_name='adminapp/post_approval.html'
  success_url = reverse_lazy('adminapp:listapprovedpost')
  # success_url = reverse_lazy('postapp:publishedposts')

  def test_func(self):
    test = self.request.user.groups.filter(name='administrator').exists() or self.request.user.is_superuser
    return test
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    ppost = get_object_or_404(PublishedPost, pk=self.kwargs['pk'])
    context['ppost'] = ppost
    if context['ppost'].approval != 'PENDING':
      context['form']['approval'].initial=context['ppost'].approval
      print(type(context['form']['approval'].initial))
      try:
        if ppost.featured:
          pass
      except:
        print("Not Featured")

      else:
        if ppost.featured.featured==True:
          context['form']['feature'].initial=True
    # print("Before approval value in db: " + context['ppost'].approval)
    return context

  def form_valid(self,form):
    approval = form.cleaned_data['approval']
    feature = form.cleaned_data['feature']
    ppost = get_object_or_404(PublishedPost, pk=self.kwargs['pk'])
    is_featured=False
    try:
      fpost = ppost.featured
    except:
      print("Not Featured")
      fpost = False
    else:
      if fpost and fpost.featured:
        is_featured=True
      
      # print("Approval value returned: "+ approval)
    if approval==Approval.Approved:
      print("Approved (form)")
      if ppost.approval != Approval.Approved:
        ppost.approval = Approval.Approved
        ppost.approver = self.request.user
        ppost.save()
      if feature == True and not(is_featured):
        if not(fpost):
            fpost, created = FeaturedPost.objects.get_or_create(ppost=ppost)        
        fpost.featured=True
        fpost.save()
        print("Featured Post Set")
      elif feature == False and is_featured:
        fpost.featured = False
        fpost.save()

        # print("approval in db: " + ppost.approval)
      
    elif approval == Approval.Disapproved:
        if fpost:
          fpost.featured=False
          fpost.save()
        if ppost.approval != Approval.Disapproved:
          ppost.approval = Approval.Disapproved
          ppost.approver = self.request.user
          ppost.save()
        print("approval in db: " + ppost.approval)
    else:
      return super().form_invalid(form)
    return super().form_valid(form)

  def get_success_url(self):
    response = super().get_success_url()
    if Approval.Disapproved in self.request.POST['approval']:
      print("post is disapproved")
      response = reverse_lazy('adminapp:listdisapprovedpost')
    return response

adminapp/templates/adminapp/snippets/adminapp-comment-menu.html
<div class="flex flex-row flex-wrap gap-2 p-2 bg-gray-50 border-x border-x-stone-200 text-xs">
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="{% url 'adminapp:listcomment' 'all' %}">All</a>
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="{% url 'adminapp:listcomment' 'pending' %}">Pending</a>
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="{% url 'adminapp:listcomment' 'approved' %}">Approved</a>
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="{% url 'adminapp:listcomment' 'disapproved' %}">Disapproved</a>
</div>

adminapp/templates/adminapp/snippets/adminapp_categories_menu.html
<div class="flex flex-row flex-wrap gap-2 p-2 bg-gray-50 border-x border-x-stone-200 text-xs">
  <a class="rounded px-4 py-2 bg-lime-500 hover:bg-lime-400 text-white hover:text-white font-bold" href="{% url 'adminapp:createcategory' %}">Add New</a>
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="{% url 'adminapp:categories' %}">All</a>
</div>

adminapp/templates/adminapp/snippets/adminapp_main_menu.html
<div class="flex flex-row flex-wrap gap-2 bg-stone-100 border-x border-stone-200 text-xs">
  <a class="px-4 py-2 hover:bg-teal-800 text-stone-800 hover:text-white font-bold uppercase" href="{% url 'adminapp:listpendingpost' %}">Posts</a>
  <a class="px-4 py-2 hover:bg-teal-800 text-stone-800 hover:text-white font-bold uppercase" href="{% url 'adminapp:listcomment' 'all' %}">Comments</a>
  <a class="px-4 py-2 hover:bg-teal-800 text-stone-800 hover:text-white font-bold uppercase" href="{% url 'adminapp:categories' %}">Categories</a>
</div>

adminapp/templates/adminapp/snippets/adminapp_post_menu.html
<div class="flex flex-row flex-wrap gap-2 p-2 bg-gray-50 border-x border-x-stone-200 text-xs">
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="{% url 'adminapp:listpendingpost' %}">Pending</a>
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="{% url 'adminapp:listapprovedpost' %}">Approved</a>
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="{% url 'adminapp:listdisapprovedpost' %}">Disapproved</a>
  <a class="rounded-full px-4 py-2 hover:bg-lime-500 text-teal-700 hover:text-white font-bold" href="#">Archived</a>
</div>