adminapp/urls.py
from django.urls import path
from adminapp import views
from classapp.views import CategoryList, CreateCategoryView, EditCategoryView, DeleteCategoryView
app_name = 'adminapp'
urlpatterns=[
  path('post/listpendingpost',views.ListPendingPost.as_view(),name='listpendingpost'),
  path('post/listapprovedpost',views.ListApprovedPost.as_view(),name='listapprovedpost'),
  path('post/listdisapprovedpost',views.ListDisapprovedPost.as_view(),name='listdisapprovedpost'),

  path('comment/list/<str:approval>',views.ListComment.as_view(),name='listcomment'),

  path('post/postapproval/<int:pk>',views.PostApproval.as_view(),name='postapproval'),

  path('categories/all',CategoryList.as_view(),name='categories'),
  path('categories/new',CreateCategoryView.as_view(),name='createcategory'),
  path('categories/edit/<slug:slug>',EditCategoryView.as_view(),name='editcategory'),
  path('categories/<slug:slug>/delete',DeleteCategoryView.as_view(),name='deletecategory'),  
]

classapp/urls.py
from django.urls import path
from classapp import views

app_name = 'classapp'
urlpatterns = [
    path('categoriesmanager', views.CategoryManager.as_view(), name='categoriesmanager'),
    path('tagsmanager', views.TagManager.as_view(), name='tagsmanager'),
    
]

cmsapp/urls.py
from django.urls import path
from cmsapp import views

app_name = 'cmsapp'
urlpatterns=[
  path('home/',views.CMSHome.as_view(),name='cmshome'),
]

inksynk/urls.py
from django.contrib import admin
from django.urls import path, include

# for static files during deployment
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('site/admin', admin.site.urls),
    path('',include("siteapp.urls")),
    path('cms/',include("cmsapp.urls")),
    path('cms/user/',include("userapp.urls")),
    path('cms/post/',include("postapp.urls")),
    # path('cms/dashboard/',include("dashboard.urls")),
    path('cms/class/',include("classapp.urls")),
    path('cms/comments/',include("commentapp.urls")),
    path('cms/admin/',include("adminapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postapp/urls.py
from django.urls import path
from postapp import views

app_name = 'postapp'
urlpatterns = [
    path('postapproval/<int:pk>', views.PostApproval.as_view(), name='postapproval'),
    path('newpost',views.CreatePostView.as_view(),name='newpost'),
    path('editpost/<int:pk>',views.EditPostView.as_view(),name='editpost'),
    path('drafts',views.ListDraftPosts.as_view(),name='draftposts'),
    
    path('published',views.ListPublishedPosts.as_view(),name='publishedposts'),
    path('published/<int:pk>',views.PublishedPostView.as_view(),name='publishedpost'),
    
    path('approved',views.ListApprovedPosts.as_view(),name='approvedposts'),
    path('listpostapproval',views.ListPostApproval.as_view(),name='listpostapproval'),
    path('publishpost/<int:post_pk>',views.PublishPostView.as_view(),name='publishpost'),
    path('deletepost/delete/<int:pk>',views.DiscardDraft.as_view(),name='deletepost'),
    path('unpublishpost/unpublish/<int:pk>',views.UnpublishPost.as_view(),name='unpublishpost'),

    path('image/new/<int:post_pk>',views.CreatePostImage.as_view(),name='addpostimage'),

]

userapp/urls.py
from django.contrib import admin
from django.urls import path
from userapp import views
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

app_name = 'userapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='userapp/login.html',redirect_authenticated_user=True),name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('userprofile/<slug:slug>', views.UserProfileView.as_view(),name='userprofile'),
    
    # AJAX View for login status
    path('loginstatusquery/', views.LoginStatusQuery,name='loginstatusquery'),

    # AJAX View for user login using modal
    path('modallogin/', views.ModalLogin,name='modallogin'),
    
    # path('login',views.AuthorLogin.as_view(),name='login'),
]

cmsapp/models.py
from django.db import models

# Create your models here.

cmsapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class CMSHome(LoginRequiredMixin, TemplateView):
  template_name = 'cmsapp/cmshome.html'

cmsapp/templates/cmsapp/base.html
<!DOCTYPE html>
{% load static %}
{% load cmsAdminTags %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:wght@400;700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
  
  <link rel="stylesheet" href="{% static 'cmsapp/css/style.css'%}"/>
  <title>
    {% block windowtitle %}

    {% endblock windowtitle %}
  </title>
</head>
<body>
	<div id="wrapper" class="h-screen flex w-full">
    <div id="sidebar-wrapper" class="p-1">
      <div class="bg-teal-900 h-full rounded-md flex flex-col">
        <ul class="sidebar-nav space-y-2 pt-4">
          {% if user.is_superuser or user|is_member:'administrators' %}
          <li class="px-2"><a href={% url 'adminapp:listapprovedpost' %} class="cms-sidebar-link">Administration</a></li>
          {% endif %}
          <li class="px-2"><a href={% url 'postapp:draftposts' %} class="cms-sidebar-link">Posts</a></li>
          <li class="px-2"><a href={% url 'commentapp:usercommentlist' 'all' %} class="cms-sidebar-link">Comments</a></li>
          <li class="px-2"><a href={% url 'classapp:categoriesmanager' %} class="cms-sidebar-link">Collections</a></li>
          
        </ul>
        <ul class="sidebar-nav mt-auto">
          <li class="bg-slate-800 rounded-b-md">
            <div class="relative m-2">
              <div id="id_useraccount-menu" class="hidden w-full p-2 absolute bottom-0 space-y-2 rounded text-sm text-white bg-neutral-800">
                <a class="block p-2 rounded hover:bg-neutral-600" href="{% url 'userapp:userprofile' user.username %}">Profile</a>
                <a class="block p-2 rounded hover:bg-neutral-600" href="{% url 'userapp:logout' %}">Logout</a>
              </div>
            </div>
            <div id="id_useraccount-menu-trigger" class="p-2 space-x-2 cursor-pointer flex flex-row rounded-b-md text-sm text-white">
              <img class="rounded-full w-10" src={% static 'userapp/pictures/blank-profile-picture.png' %}>
              <div class="self-center">{{user.username}}</div>
            </div>
          </li>
        </ul>
      </div>
    </div>
		<div class="page-content-wrapper grow">
			<div class="mx-1 py-1 h-full">
        {% block pagecontent %}
        
        {% endblock pagecontent %}
      </div>
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'cmsapp\js\sidebar_menu.js'%}"></script>
  <script>
    
    $("#id_useraccount-menu-trigger").click(function(){
      $("#id_useraccount-menu").toggleClass("hidden");
    });
  </script>
  {% block pagescripts %}
  
  {% endblock pagescripts %}
</body>
</html>

cmsapp/templates/cmsapp/cmshome.html
{% extends 'cmsapp/base.html' %}
{% block windowtitle %}CMS - Home{% endblock windowtitle %}
{% block pagecontent %}
  <h1 class="text-xl">Welcome to InksynkCMS</h1>
{% endblock pagecontent %}